# cloudbuild.yaml

logsBucket: "gs://logs-entrevista"

steps:
  # 1. Navegar a la carpeta del servicio y construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'nginx-flask-mongo/flask'
    args: [
      'build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/flask-demo-app1/flask-demo-app1/:$COMMIT_SHA', '.'
    ]

  # 2. Subir la imagen de Docker a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-east1-docker.pkg.dev/$PROJECT_ID/flask-demo-app1/flask-demo-app1/:$COMMIT_SHA'
    ]

  # 3. Actualizar el despliegue en GKE solo para service1
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/backend'
      - 'backend=us-east1-docker.pkg.dev/$PROJECT_ID/flask-demo-app1/flask-demo-app1/:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/flask-demo-app1/flask-demo-app1/:$COMMIT_SHA'

timeout: '1200s'