apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
  namespace: node-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: us-east1-docker.pkg.dev/entrevista123/node-redis-app/app:latest
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 512Mi
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web1-service
  namespace: node-redis
spec:
  selector:
    app: web1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  # type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web1-hpa
  namespace: node-redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web1
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
